### ISSUE TITLE
IGV .vcf FileNotFoundError

### ISSUE THREAD

**Issue by ryanjameskennedy** [Clinical-Genomics-Lund/bonsai#206]
**Describe the bug**
Error 500 Errmsg display box pops up when viewing a variant in IGV.

**To Reproduce**
1. Select any sample.
2. Click on "Variants" in the top-left corner.
3. Under tbprofiler, click on "IGV" of any variant on the right side of each row.

**Expected behavior**
No error pops up.

**Screenshots**
![image](https://github.com/user-attachments/assets/362bf1f3-e057-45db-babf-2bb26a6c388a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: Doesn't matter

**Additional context**
The following command was run:
```
docker logs <docker_container_id> --tail 40
```
Output from Bonsai api logs:
```
File "/home/worker/app/bonsai_api/io.py", line 60, in is_file_readable
    raise FileNotFoundError(file_path)
FileNotFoundError: /access/jasen/mtuberculosis/vcf/<limsid_seqrun>_annotated_delly.vcf
```

**Comment by mhkc** [comment]
Is the file in `/access`?
