### ISSUE TITLE
Internal server error `requests.exceptions.HTTPError: 414 Client Error: Request-URI Too Long for url` when trying to cluster large quantity of samples from basket

### ISSUE THREAD

**Issue by alkc** [Clinical-Genomics-Lund/bonsai#80]
**Describe the bug**

Client crashes with `requests.exceptions.HTTPError: 414 Client Error: Request-URI Too Long for url` when sending a large number of samples to clustering. Error occurs in `get_samples_by_id` at L145 in `cluster/views.py`

**To Reproduce**
1. Set up bonsai instance and saturate with samples
2. Add ~760 samples to basket
3. Open basket and select cluster

**Expected behavior**

Cluster view should be displayed if possible, or cluster button should be disabled. 

In any case the client should handle the error better.

**Desktop (please complete the following information):**
 - Firefox 118.0.1

**Comment by mhkc** [comment]
Fixed with #83
