### ISSUE TITLE
Bulk mark samples that passed or failed QC

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics-Lund/bonsai#97]
**Please describe your role and what you want to do**
Mark multiple samples as have passed QC.

**Comment by alkc** [comment]
I'm thinking of adding smth like this (with a text label):

![bild](https://github.com/Clinical-Genomics-Lund/bonsai/assets/13668555/f249287c-5524-4009-927a-6faf5e5a8d5d)

Selecting one or more samples and marking them as failed would show a dialog with the same controls as the sidebar QC menu from /samples/:

![bild](https://github.com/Clinical-Genomics-Lund/bonsai/assets/13668555/c152a690-baa6-4026-ad3b-81c16e031735)

Marking QC as passed would show a similar box only containing the confirm button.

**Comment by alkc** [comment]
## Draft TODO:

- [ ] New macro in /groups/templates/shared.html
- [ ] Is there any QC endpoint that supports multiple samples
- [ ] Do `bad_qc_actions` need to be moved into config?

**Comment by alkc** [comment]
Hmm. Trying to toggle a dropdown using the built in methods in bootstrap is proving too hard for me. Might be a better idea (in therms of just getting this done) to hide the thumbs buttons in the dropdown and just make a navbar button to toggle the dropdown and nothing else.

**Comment by alkc** [comment]
Some progress:

![bonsai-qc](https://github.com/Clinical-Genomics-Lund/bonsai/assets/13668555/b802f330-de1b-495e-9a3d-4787e5edb6be)

Setting QC for multiple samples works. A whole-page reload is involved, but sample selection is retained upon reload
